# This is a basic workflow to help you get started with Actions

name: build_x86

# Controls when the action will run. 
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-2019
    defaults:
      run:
        shell: msys2 {0}
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Check Out
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: true

      - name: Setup MSYS2
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW32
          update: true
          install: >-
            base-devel
            git
            p7zip
            mingw32/mingw-w64-i686-bzip2
            mingw32/mingw-w64-i686-curl
            mingw32/mingw-w64-i686-diffutils
            mingw32/mingw-w64-i686-gcc
            mingw32/mingw-w64-i686-libass
            mingw32/mingw-w64-i686-nasm
            mingw32/mingw-w64-i686-pkg-config
            mingw32/mingw-w64-i686-SDL2

      - name: Setup
        run: ./setup_x86.sh

      - name: Configure
        run: ./configure_x86.sh

      - name: Upload ffbuild/config.log
        uses: actions/upload-artifact@v2
        with:
          name: Configure.log
          path: ffmpeg/ffbuild/config.log
  
      - name: Build
        run: ./build_x86.sh

      - name: Upload build file
        uses: actions/upload-artifact@v2
        with:
          name: install-file-x86
          path: ffbuild-x86.7z
